kind: pipeline
type: kubernetes
name: hal24k-bot

steps:
- name: build-hal24k-bot
  image: plugins/docker
  when:
    branch:
    - main
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:  docker-registry.dimension.ws/hal24k-bot
    tag: latest
    registry: docker-registry.dimension.ws

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: build-status
  when:
    status: [ success, failure ]